name: Generate PlantUML SVG

on:
  push:
    paths:
      - "lumidigui/docs/*.puml"

permissions:
  contents: write

jobs:
  generate-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Download PlantUML
        run: curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar

      - name: Generate SVGs from PUML files
        run: |
          for puml in lumidigui/docs/*.puml; do
            svg="${puml%.puml}.svg"
            java -jar plantuml.jar -tsvg "$puml"
          done

      - name: Commit and push updated SVGs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add lumidigui/docs/*.svg
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update PlantUML SVGs [automated]"
            git push
          fi
